name: 'Deploy Action'
description: 'This is my reusable action'
inputs:
  flavor:
    description: 'flavor'
    required: true
    default: 'blink'
  firebase_file:
    description: 'firebase google service file'
    required: true
    default: 'blink'
runs:
  using: "composite"
  steps:

    - name: Download blink Android keystore
      id: android_blink_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: blink-keystore.jks
        encodedString: ${{ secrets.KEYSTORE_BASE64_BLINK }}

    - name: Download unity Android keystore
      id: android_unity_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: unity-keystore.jks
        encodedString: ${{ secrets.KEYSTORE_BASE64_UNITY }}

    - name: Download sportico Android keystore
      id: android_sportico_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: sportico-keystore.jks
        encodedString: ${{ secrets.KEYSTORE_BASE64_SPORTICO }}


    - name: Create key.properties
      run: |
        echo "storeFile=${{ steps.android_blink_keystore.outputs.filePath }}" > android/key1.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD_BLINK }}" >> android/key1.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD_BLINK }}" >> android/key1.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS_BLINK }}" >> android/key1.properties
        
        echo "storeFile=${{ steps.android_unity_keystore.outputs.filePath }}" > android/key2.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD_UNITY }}" >> android/key2.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD_UNITY }}" >> android/key2.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS_UNITY }}" >> android/key2.properties
        
        echo "storeFile=${{ steps.android_sportico_keystore.outputs.filePath }}" > android/key3.properties
        echo "storePassword=${{ secrets.STORE_PASSWORD_SPORTICO }}" >> android/key3.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD_SPORTICO }}" >> android/key3.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS_SPORTICO }}" >> android/key3.properties
      shell: bash

    - uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: "17"
        cache: gradle
        check-latest: true

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: "3.16.1"
        channel: 'stable'
        cache: true

    - name: Download firebase google services for blink
      run: echo "${{inputs.firebase_file}}" | base64 -d > android/app/src/${{ inputs.flavor }}/google-services.json
      shell: bash

    - name: Get dependencies
      run: flutter pub get
      shell: bash
    - name: Start Android Release Build
      run: flutter build apk --flavor ${{ inputs.flavor }} -t lib/main.dart
      shell: bash