name: 'Deploy Action'
description: 'This is my reusable action'
inputs:

  urls:
    description: 'urls'
    required: true
    default: ''

  filepath:
    description: 'file path'
    required: true

  language:
    description: 'Language'
    required: true
    default: 'en-US'


runs:
  using: "composite"
  steps:

#    - name: Download firebase google services file
#      run: echo "${{inputs.firebase_file}}" | base64 -d > android/app/src/${{ inputs.flavor }}/google-services.json
#      shell: bash

    - name: Split URL string and store in env
      id: split-text
      run: |
        URLS="${{ inputs.urls  }}"
        IFS="#" read -r -a URL_LIST <<< "$URLS"
        echo " level:  ${{ inputs.urls }}"
        echo "image1=${URL_LIST[0]}" >> $GITHUB_ENV
        echo "image2=${URL_LIST[1]}" >> $GITHUB_ENV
        echo "image3=${URL_LIST[2]}" >> $GITHUB_ENV
        echo "image4=${URL_LIST[3]}" >> $GITHUB_ENV
        echo "image5=${URL_LIST[4]}" >> $GITHUB_ENV
        echo "image6=${URL_LIST[5]}" >> $GITHUB_ENV
        echo "image7=${URL_LIST[6]}" >> $GITHUB_ENV
        echo "image8=${URL_LIST[7]}" >> $GITHUB_ENV
        echo "::set-output name=SPLIT_TEXTS::${URL_LIST[@]}"
      shell: bash

    - name: Download image 1
      if: ${{ env.image1 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image1 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 1_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 2
      if: ${{ env.image2 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image2 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 2_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 3
      if: ${{ env.image3 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image3 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 3_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 4
      if: ${{ env.image4 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image4 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 4_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 5
      if: ${{ env.image5 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image5 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 5_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 6
      if: ${{ env.image6 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image6 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 6_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 7
      if: ${{ env.image7 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image7 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 7_${{ inputs.language }}.png   # Optional, keep original filename (optional)

    - name: Download image 8
      if: ${{ env.image8 }} != ''
      continue-on-error: true
      uses: suisei-cn/actions-download-file@v1
      with:
        url: ${{ env.image8 }}
        target: ${{ inputs.filepath }} # Optional, download directory
        filename: 8_${{ inputs.language }}.png   # Optional, keep original filename (optional)


#    - name: Download file 0
#    #  if:  0 -lt ${{ env.DOWNLOAD_URLS@length }}
#      run: |
#        echo "Log level:  ${{ steps.split-text.outputs.SPLIT_TEXTS[0] }}"
#        echo "Log level:   ${{ env.WORK_APPS }}"
#      shell: bash

#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[0] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 0_en_US.png   # Optional, keep original filename (optional)

#    - name: Download file 1
#    #  if: 1 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[1] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 1_en_US.png   # Optional, keep original filename (optional)
#
#    - name: Download file 2
#      #if:  2 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[2] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 2_en_US.png   # Optional, keep original filename (optional)

#    - name: Download file 3
#    #  if:  3 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[3] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 3_en_US.png   # Optional, keep original filename (optional)
#      shell: bash
#
#    - name: Download file 4
#    #  if:  4 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[4] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 4_en_US.png   # Optional, keep original filename (optional)



#- name: Download files from URLs
#        uses: suisei-cn/actions-download-file@v1  # Assuming download action
#        with:
#          url: ${{ env.DOWNLOAD_URLS }}  # Access environment variable
#          target: ./downloads/  # Optional, download directory
#          filename: ""  # Optional, keep original filenames

#    - name: Set Application feature Graphic
#      if: github.event.inputs.feature_graphic != ''
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ inputs.url }}
#        target: inputs.filepath
#        filename: inputs.filename

