name: 'Deploy Action'
description: 'This is my reusable action'
inputs:

  urls:
    description: 'urls'
    required: true
    default: ''

  filepath:
    description: 'file path'
    required: true

  language:
    description: 'Language'
    required: true
    default: 'en-US'


runs:
  using: "composite"
  steps:

#    - name: Download firebase google services file
#      run: echo "${{inputs.firebase_file}}" | base64 -d > android/app/src/${{ inputs.flavor }}/google-services.json
#      shell: bash

    - name: Split URL string and store in env
      id: split-text
      run: |
        IFS="#" read -ra url_list <<< "${{ inputs.urls }}"
        echo "1 level:  ${{ url_list[0] }}"
        echo "2 level:  ${{ url_list[1] }}"
        echo "3 level:  ${{ url_list[2] }}"
        echo "::set-output name=SPLIT_TEXTS::${url_list[@]}"
      #  echo "::set-output name=DOWNLOAD_URLS::${url_list[@]}"

      shell: bash

    - name: Download file 0
    #  if:  0 -lt ${{ env.DOWNLOAD_URLS@length }}
      run: |
        echo "Log level:  ${{ steps.split-text.outputs.SPLIT_TEXTS[0] }}"
      shell: bash

#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[0] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 0_en_US.png   # Optional, keep original filename (optional)

#    - name: Download file 1
#    #  if: 1 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[1] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 1_en_US.png   # Optional, keep original filename (optional)
#
#    - name: Download file 2
#      #if:  2 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[2] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 2_en_US.png   # Optional, keep original filename (optional)

#    - name: Download file 3
#    #  if:  3 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[3] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 3_en_US.png   # Optional, keep original filename (optional)
#      shell: bash
#
#    - name: Download file 4
#    #  if:  4 -lt ${{ env.DOWNLOAD_URLS@length }}
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ env.DOWNLOAD_URLS[4] }}
#        target: ${{ inputs.url }} # Optional, download directory
#        filename: 4_en_US.png   # Optional, keep original filename (optional)



#- name: Download files from URLs
#        uses: suisei-cn/actions-download-file@v1  # Assuming download action
#        with:
#          url: ${{ env.DOWNLOAD_URLS }}  # Access environment variable
#          target: ./downloads/  # Optional, download directory
#          filename: ""  # Optional, keep original filenames

#    - name: Set Application feature Graphic
#      if: github.event.inputs.feature_graphic != ''
#      uses: suisei-cn/actions-download-file@v1
#      with:
#        url: ${{ inputs.url }}
#        target: inputs.filepath
#        filename: inputs.filename

