# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
release_notes({
  'default' => " new version from fastlane default and new",
  'default' => "new version from fastlane new",
  'en-US' => "new version from fastlane"
})