# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
release_notes({
  'default' => "Shiny and new",
  'en-US' => "Shiny and new"
})