name: update App info to Apple Store
on:
  workflow_dispatch:
    inputs:
      appBundleId:
        description: 'App Bundle Id'
        required: true

      subtitle:
        type: string
        required: true
        description: "new app subtitle"

      description:
        type: string
        description: "new app description"
        required: true

      promotionalText:
        type: string
        description: "new app promotional Text"

      keywords:
        type: string
        description: "new app keywords"
        required: true

      supportUrl:
        type: string
        description: "new app support url"
        required: true

      marketingUrl:
        type: string
        description: "new app marketing url"

      privacyUrl:
        type: string
        description: "new app privacy url"

      releaseNotes:
        type: string
        description: "new app release notes"




jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2


      - name: Create App store json
        run: echo  "${{ secrets.APPLE_STORE_API_KEY_JSON }}" > ios/api_key.json


      - name: get current data
        run: fastlane deliver init --api_key_path api_key.json  --app_identifier --app_identifier ${{ github.event.inputs.appBundleId  }}


      - name: Create subtitle file
        run: echo  "${{ github.event.inputs.subtitle }}" > ios/fastlane/metadata/en-US/subtitle.txt

      - name: Create description file
        run: echo  "${{ github.event.inputs.description }}" > ios/fastlane/metadata/en-US/description.txt

      - name: Create app name file
        run: echo  "${{ github.event.inputs.promotionalText }}" > ios/fastlane/metadata/en-US/promotional_text.txt

      - name: Create keywords file
        run: echo  "${{ github.event.inputs.keywords }}" > ios/fastlane/metadata/en-US/keywords.txt

      - name: Create support  url file
        run: echo  "${{ github.event.inputs.supportUrl }}" > ios/fastlane/metadata/en-US/support_url.txt

      - name: Create marketing url file
        run: echo  "${{ github.event.inputs.marketingUrl }}" > ios/fastlane/metadata/en-US/marketing_url.txt

      - name: Create app name file
        run: echo  "${{ github.event.inputs.privacyUrl }}" > ios/fastlane/metadata/en-US/privacy_url.txt

      - name: Create release notes file
        run: echo  "${{ github.event.inputs.releaseNotes }}" > ios/fastlane/metadata/en-US/release_notes.txt


#    Fixed Data
      - name: Create copyright file
        run: echo  "Blink Copy Rights 2024 All Right Reserved" > ios/fastlane/metadata/copyright.txt

      - name: Create primary category file
        run: echo  "TRAVEL" > ios/fastlane/metadata/primary_category.txt

      - name: Create secondary category file
        run: echo  "ENTERTAINMENT" > ios/fastlane/metadata/secondary_category.txt


      - name: Create email address file
        run: echo  "info@blink.com" > ios/fastlane/metadata/review_information/email_address.txt

      - name: Create fist name file
        run: echo  "Blink" > ios/fastlane/metadata/review_information/first_name.txt


      - name: Create last name file
        run: echo  "LLC" > ios/fastlane/metadata/review_information/last_name.txt

      - name: Create phone number file
        run: echo  "+201211900099" > ios/fastlane/metadata/review_information/phone_number.txt



      - name: Deploy Screenshots to Apple Store
        run: |
          cd ios
          gem install fastlane
          fastlane deliver --api_key_path api_key.json  --app_identifier ${{ github.event.inputs.appBundleId  }} --force true --app_version 1.0.1 --skip_app_version_update true --automatic_release false --skip_screenshots true  --app_rating_config_path fastlane/app_rating_config.json --run_precheck_before_submit false --precheck_include_in_app_purchases false --price_tier 0