name: Deploy categories to Apple Store
on:
  workflow_dispatch:
    inputs:
      appBundleId:
        description: 'App Bundle Id'
        required: true
#      general info
#    1.
      copyright:
        type: string
        description: "new copyright"
#    2.
      primaryCategory:
        type: string
        description: "new primary category"
#    3.
      primaryFirstSubCategory:
        type: string
        description: "new app primary first sub category"
#    4.
      primarySecondSubCategory:
        type: string
        description: "new app second first sub category"
#    5.
      secondaryCategory:
        type: string
        description: "new app secondary category"
#    6.
      secondaryFirstSubCategory:
        type: string
        description: "new app secondary first sub category"
#    7.
      secondarySecondSubCategory:
        type: string
        description: "new app secondary second sub category"




jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2


      - name: Create App store json
        run: echo  "${{ secrets.APPLE_STORE_API_KEY_JSON }}" > ios/api_key.json


#      app general info  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> start




#     1. copyright
      - name: Create copyright file
        run: echo  "${{ github.event.inputs.copyright  }}" > ios/fastlane/metadata/copyright.txt

#     2. primary category
      - name: Create primary category file
        run: echo  "${{ github.event.inputs.primaryCategory }}" > ios/fastlane/metadata/primary_category.txt

#     3. primary first sub category
      - name: Create  primary first sub category file
        run: echo  "${{ github.event.inputs.primaryFirstSubCategory }}" > ios/fastlane/metadata/primary_first_sub_category.txt

#     4.  primary Second sub category
      - name: Create  primary first sub category file
        run: echo  "${{ github.event.inputs.primarySecondSubCategory }}" > ios/fastlane/metadata/primary_second_sub_category.txt


#     5. secondary category
      - name: Create secondary category file
        run: echo  "${{ github.event.inputs.secondaryCategory}" > ios/fastlane/metadata/secondary_category.txt

#     6. secondary first sub category
      - name: Create secondary first sub category  file
        run: echo  "${{ github.event.inputs.secondaryFirstSubCategory }}" > ios/fastlane/metadata/secondary_first_sub_category.txt

#     7. secondary second sub category
      - name: Create secondary second sub category file
        run: echo  "${{ github.event.inputs.secondarySecondSubCategory }}" > ios/fastlane/metadata/secondary_second_sub_category.txt

#      app general info  >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> end


      - name: Deploy categories to Apple Store
        run: |
          cd ios
          gem install fastlane
          fastlane deliver --api_key_path api_key.json  --app_identifier ${{ github.event.inputs.appBundleId  }} --force true --app_version 1.0.1 --skip_app_version_update true --automatic_release false --skip_screenshots true
      
      
      
      
