on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build IOS"
jobs:
  build:
    name: Build IOS
    runs-on: macos-latest
    environment: hallo
    env:
      FIREBASE: ${{secrets.FIREBASE_GOOGLE_SERVICES}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.1"
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: build Ios ipa
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          In -s ../Runner-app
          cd ..
          zip -r app.ipa Payload
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: ios-release
          path: build/ios/iphoneos/app.ipa