on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build With Condition"
jobs:
  build_blink:
    name: Build Blink
    if: contains($(git log -1 --pretty=%B), 'blink') || contains($(git log -1 --pretty=%B), 'all')
    runs-on: ubuntu-latest
    environment: hallo
    env:
      BLINK_FIREBASE: ${{secrets.FIREBASE_GOOGLE_SERVICES_BLINK}}
    steps:
      - uses: actions/checkout@v1
        # Make sure the @v0.8.0 matches the current version of the action
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check Commit Message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MESSAGE"

      - name: Download blink Android keystore
        id: android_blink_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: blink-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_BLINK }}


      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_blink_keystore.outputs.filePath }}" > android/key1.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_BLINK }}" >> android/key1.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_BLINK }}" >> android/key1.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_BLINK }}" >> android/key1.properties
          
          echo "storeFile=${{ steps.android_unity_keystore.outputs.filePath }}" > android/key2.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_UNITY }}" >> android/key2.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_UNITY }}" >> android/key2.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_UNITY }}" >> android/key2.properties
          
          echo "storeFile=${{ steps.android_sportico_keystore.outputs.filePath }}" > android/key3.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_SPORTICO }}" >> android/key3.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_SPORTICO }}" >> android/key3.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_SPORTICO }}" >> android/key3.properties

      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.1"
          channel: 'stable'
          cache: true

      - name: Download firebase google services for blink
        run: echo "$BLINK_FIREBASE" | base64 -d > android/app/src/blink/google-services.json


      - name: Get dependencies
        run: flutter pub get
      # Build Apk blink
      - name: Start Android Release Build Blink
        run: flutter build apk --flavor blink -t lib/main.dart


        # Upload Android Blink
      - name: Upload Android Blink Release
        uses: actions/upload-artifact@v2
        with:
          name: android-blink-release
          path: build/app/outputs/flutter-apk/app-blink-release.apk

          # Distribution Blink
      - name: Firebase Blink Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_BLINK_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-blink-release.apk
          releaseNotes: "test note \n version :50 \n new in version : test"


  build_unity :
    name: Build Unity
    runs-on: ubuntu-latest
    environment: hallo
    if: contains($(git log -1 --pretty=%B), 'unity') || contains($(git log -1 --pretty=%B), 'all')
    env:
      UNITY_FIREBASE: ${{secrets.FIREBASE_GOOGLE_SERVICES_UNITY}}
    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download blink Android keystore
        id: android_blink_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: blink-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_BLINK }}

      - name: Download unity Android keystore
        id: android_unity_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: unity-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_UNITY }}

      - name: Download sportico Android keystore
        id: android_sportico_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: sportico-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_SPORTICO }}


      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_blink_keystore.outputs.filePath }}" > android/key1.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_BLINK }}" >> android/key1.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_BLINK }}" >> android/key1.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_BLINK }}" >> android/key1.properties
          
          echo "storeFile=${{ steps.android_unity_keystore.outputs.filePath }}" > android/key2.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_UNITY }}" >> android/key2.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_UNITY }}" >> android/key2.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_UNITY }}" >> android/key2.properties
          
          echo "storeFile=${{ steps.android_sportico_keystore.outputs.filePath }}" > android/key3.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_SPORTICO }}" >> android/key3.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_SPORTICO }}" >> android/key3.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_SPORTICO }}" >> android/key3.properties

      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.1"
          channel: 'stable'
          cache: true
      - name: Download firebase google services for unity
        run: echo "$UNITY_FIREBASE" | base64 -d > android/app/src/unity/google-services.json


      - name: Get dependencies
        run: flutter pub get
        # Build Apk unity
      - name: Start Android Release Build Unity
        run: flutter build apk --flavor unity -t lib/main.dart

          # Upload Android Unity
      - name: Upload Android Unity Release
        uses: actions/upload-artifact@v2
        with:
          name: android-unity-release
          path: build/app/outputs/flutter-apk/app-unity-release.apk

          # Distribution Unity
      - name: Firebase Unity Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_UNITY_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-unity-release.apk








