on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Distribute (Firebase Distribution)"
jobs:
  build:
    name: Build & Distribute
    runs-on: ubuntu-latest
    environment: hallo
    env:
      APP_NAME: ${{vars.APP_NAME}}
      PACKAGE_NAME: ${{vars.PACKAGE_NAME}}
      LOGO: ${{vars.LOGO}}
      DOTENV: ${{vars.DOTENV}}
      FIREBASE: ${{secrets.FIREBASE_GOOGLE_SERVICES}}
    steps:
      - uses: actions/checkout@v1
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}
      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.1"
          channel: 'stable'
          cache: true
      - name: Download firebase google services
        run: echo "$FIREBASE" | base64 -d > android/app/google-services.json
      - name: Get dependencies
        run: flutter pub get
      - name: Generate App Assets
        run: flutter pub run flutter_launcher_icons
      - name: Start Android Release Build
        run: flutter build apk
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk
#      - name: push to Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/*"
#          tag: v1.0.${{github.run_number}}
#          token: ${{secrets.TOKEN}}
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk



