on:
  pull_request:
    branches:
      - main
      - master
#  push:
#    branches:
#      - main
#      - master
#      - develop
name: "Build & Deploy app to google play"
jobs:
  build:
    name: Build & Deploy app on google play
    runs-on: ubuntu-latest
    environment: hallo
    env:
      BLINK_FIREBASE: ${{secrets.FIREBASE_GOOGLE_SERVICES_BLINK}}
    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download blink Android keystore
        id: android_blink_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: blink-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_BLINK }}

      - name: Download unity Android keystore
        id: android_unity_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: unity-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_UNITY }}

      - name: Download sportico Android keystore
        id: android_sportico_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: sportico-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64_SPORTICO }}


      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_blink_keystore.outputs.filePath }}" > android/key1.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_BLINK }}" >> android/key1.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_BLINK }}" >> android/key1.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_BLINK }}" >> android/key1.properties

          echo "storeFile=${{ steps.android_unity_keystore.outputs.filePath }}" > android/key2.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_UNITY }}" >> android/key2.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_UNITY }}" >> android/key2.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_UNITY }}" >> android/key2.properties

          echo "storeFile=${{ steps.android_sportico_keystore.outputs.filePath }}" > android/key3.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD_SPORTICO }}" >> android/key3.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD_SPORTICO }}" >> android/key3.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS_SPORTICO }}" >> android/key3.properties

      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.16.1"
          channel: 'stable'
          cache: true

      - name: Download firebase google services for blink
        run: echo "$BLINK_FIREBASE" | base64 -d > android/app/src/blink/google-services.json

      # Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get


      # Build bundle blink
      - name: Start Android Release Build Blink
        run: flutter build appbundle --flavor blink -t lib/main.dart

      #deploy to google play
      - name: Release Build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.PLAYSTORE_ACCOUNT_KEY}}
          packageName: com.getaction.hello
          releaseFiles: build/app/outputs/bundle/blinkRelease/app-blink-release.aab
          track: production
          status: completed
          changesNotSentForReview: true




#          track: production
#          status: completed


#Status 'inProgress' requires a 'userFraction' to be set
#Status 'halted' requires a 'userFraction' to be set
#Only releases with status draft may be created on draft app.



