name: Deploy Screenshots to Google Play
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
#  push:
#    branches:
#      - main
#      - master # change this if your main branch has a different name

jobs:
  release:
    runs-on: ubuntu-latest
    environment: hallo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: printInputs
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}" 
        

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

#      - name: Install Fastlane
#        run: gem install fastlane

      - name: Deploy Screenshots to Google Play
        run: |
          mkdir json
          echo '${{ secrets.PLAYSTORE_ACCOUNT_KEY }}' > android/play-store-credentials.json
          cd android
          fastlane supply --skip_upload_changelogs true
          
        #fastlane supply init
        #echo '${{ secrets.PLAYSTORE_ACCOUNT_KEY }}' > json/key.json
        #fastlane supply --metadata_path fastlane/metadata/android --json_key json/key.json --skip_upload_changelogs true


        #workflow id  =>  change-screenshots-google-store