name: Deploy Screenshots to Google Play
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
      package_id:
        description: 'Application Package Id'
        default: 'com.getaction.hello'
        required: true
      title:
        description: 'Application title'
        default: ''
      short_description:
        description: 'Application Short Description'
        default: ''
      full_description:
        description: 'Application Full Description'
        default: ''


#  push:
#    branches:
#      - main
#      - master # change this if your main branch has a different name

jobs:
  release:
    runs-on: ubuntu-latest
    environment: hallo
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

#      - name: printInputs
#        run: |
#          echo "Log level: ${{ github.event.inputs.logLevel }}"
#          echo "Tags: ${{ github.event.inputs.tags }}"
        

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

#      - name: Install Fastlane
#        run: gem install fastlane

#      - name: Set Application Package Id
#        run: |
#          echo 'package_name("${{ github.event.inputs.package_id}}")' > android/fastlane/Appfile
#          echo 'json_key_file("play-store-credentials.json")' > android/fastlane/Appfile


      - name: Set Application Title
        if: github.event.inputs.title != ''
        run: |
          echo '${{ github.event.inputs.title }}' > android/fastlane/metadata/android/en-US/title.txt

      - name: Set Application Short Description
        if: github.event.inputs.short_description != ''
        run: |
          echo '${{ github.event.inputs.short_description }}' > android/fastlane/metadata/android/en-US/short_description.txt

      - name: Set Application Full Description
        if: github.event.inputs.full_description != ''
        run: |
          echo '${{ github.event.inputs.full_description }}' > android/fastlane/metadata/android/en-US/full_description.txt

      - name: Deploy Screenshots to Google Play
        run: |
          echo '${{ secrets.PLAYSTORE_ACCOUNT_KEY }}' > android/play-store-credentials.json
          cd android
          fastlane supply --skip_upload_changelogs true

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "{workflow} has {status_message}"
          footer: "Linked Repo <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
        #fastlane supply init
        #echo '${{ secrets.PLAYSTORE_ACCOUNT_KEY }}' > json/key.json
        #fastlane supply --metadata_path fastlane/metadata/android --json_key json/key.json --skip_upload_changelogs true

       # fastlane supply --skip_upload_changelogs true --package_name com.getaction.hello --json_key play-store-credentials.json
        #workflow id  =>  change-screenshots-google-store