# 1  Created a new job version that will be executed before the build job
version:
  name: Create version number
  # The type of runner that the job will run on
  runs-on: ubuntu-latest
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    - uses: actions/checkout@v3
    # 2 Installed the GitVersion, a tool used for versioning by looking at your Git history
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.7
    # 3 Posted using GitVersion, placing the version in a version.text file
    - name: Create version.txt with nuGetVersion
      run: echo ${{ steps.gitversion.outputs.nuGetVersion  }} > version.txt
    # 4 Uploaded the version.text file as an artifact for the actions system with a name gitversion to be used later in the build job
    - name: Upload version.txt
      uses: actions/upload-artifact@v2
      with:
        name: gitversion
        path: version.txt