name: Get latest TestFlight build number
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Create App store json
      run: |
        echo '${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}' > api_private_key.p8
        echo "{\"key_id\": \'${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}\',\"issuer_id\": \'${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}\',\"key_filepath\": \"api_private_key.p8\"} " > api_key.json

    - name: Install Fastlane
      run: gem install fastlane

    - name: Get latest TestFlight build number
#      env:
#        FASTLANE_USER: ${{ secrets.APPSTORE_USERNAME }}
#        FASTLANE_PASSWORD: ${{ secrets.APPSTORE_PASSWORD }}
      run: |
        fastlane run latest_testflight_build_number \
        app_identifier:"com.nxt.ci" \
        api_key_path:"api_key.json"
#         api_key:"
#        {
#            \"key\": \"${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}\",
#            \"key_id\": \"${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}\",
#            \"issuer_id\": \"${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}\"
#        }
#         "
        


#  fastlane run latest_testflight_build_number \
#  username:"${{ secrets.APPSTORE_USERNAME }}" \
#  team_name:"Hussein Reda" \
#  team_id:"126599802" \
#