name: Get latest TestFlight build number
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0

    - name: Replace Newlines
      run: |
        echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" | sed ':a;N;$!ba;s/\n/\\n/g
#
#
#    - name: Install Fastlane
#      run: gem install fastlane
#
#
#    - name: Create App store json
#      if: ${{ always() }}
#      run: |
#        echo ' { "key_id": "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}", "issuer_id": "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}",  "key": "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcflv+5BltPCFHzpD\nz5wfS+rCmoXzvIaBakAni+XUPU+gCgYIKoZIzj0DAQehRANCAARWWdou7iRZbbe7\n0REBr3SZNRNwNzpnmGlnepNFGiUgZ21+/Gdg2lYHN/0H+L/t9X8CExqyFEFD7Ylu\nfH4SVTwj\n-----END PRIVATE KEY-----"  , "in_house": false } ' > api_key.json
#
#    - name: Get latest TestFlight build number
#      if: ${{ always() }}
#      run: |
#        fastlane run latest_testflight_build_number \
#        app_identifier:"com.nxt.ci" \
#        api_key_path:"api_key.json"
