name: Get latest TestFlight build number
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0


    - name: Install Fastlane
      run: gem install fastlane


    - name: Create App store json
      if: ${{ always() }}
      run: |
        api_private_key=$(echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" | tr '\n' '\\n')
        echo ' { "key_id": "${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}", "issuer_id": "${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}",  "key": "${{api_private_key}}"  , "in_house": false } ' > api_key.json

      # Collect the file and upload as artifact
    - name: collect ipa artifacts
      uses: actions/upload-artifact@v2
      with:
        name: api_key
        path: api_key.json

    - name: Get latest TestFlight build number
      if: ${{ always() }}
      run: |
        fastlane run latest_testflight_build_number \
        app_identifier:"com.nxt.ci" \
        api_key_path:"api_key.json"
