name: Get latest TestFlight build number
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0


    - name: Install Fastlane
      run: gem install fastlane


    - name: Create App store json
      run:  echo  "${{ secrets.APPLE_STORE_API_KEY_JSON }}" > api_key.json

#      # Collect the file and upload as artifact
#    - name: collect ipa artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: api_key
#        path: api_key.json



    - name: Get latest TestFlight build number
      id: testflight
      run: |
        echo "::set-output name=build_number::$(fastlane run latest_testflight_build_number api_key_path:"api_key.json" app_identifier:"com.nxt.ci" | grep "Result: " | awk '{print $3}'  )"


    - name: Print Build Number
      run: echo "The latest TestFlight build number is ${{ steps.testflight.outputs.build_number}} "

    - name: Increment build number
      id: testflight_incremented
      run: |
        INCREMENTED_NUMBER=$(expr $((10#${{ steps.testflight.outputs.build_number }})) + 1)
        echo "::set-output name=build_number::$INCREMENTED_NUMBER"

    - name: Print incremented value
      run: echo "Incremented build number is ${{ steps.increment.outputs.build_number }}"

    - name: Print Build Number
      run: echo "The latest TestFlight build number is ${{ steps.testflight_incremented.outputs.build_number}} "
