on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release"
jobs:
  build:
    name: Build & Release (Change APP Name)
    runs-on: macos-latest
    environment: hallo
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
       #   cache: 'gradle' # 1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.6'
      #    channel: 'stable'
       #   cache: true # 2
      - run: sed -i.bak "s/android:label=.*/android:label=\"${vars.APP_NAME}\"/g" android/app/src/main/AndroidManifest.xml
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
#      - run: flutter build apk
#      - run: flutter build appbundle
      - name: push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}

#echo "android {  defaultConfig { applicationId '${PACKAGE_NAME}' }  }" > android/changePackage.gradle
  #          echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle
  #push to master , main, develop
  #pull request on main master