on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release (Change APP Name)"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    environment: hallo
    env:
      APP_NAME: ${{vars.APP_NAME}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.6"
          channel: 'stable'
          cache: true
     # - run: sed -i.bak "s/android:label=.*/android:label=\"${vars.APP_NAME}\"/g" android/app/src/main/AndroidManifest.xml
      - run: sed -i.bak "s/android:label=.*/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml
      - run: flutter pub get
      - name: Start Android Release Build
        run: flutter build apk
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

#echo "android {  defaultConfig { applicationId '${PACKAGE_NAME}' }  }" > android/changePackage.gradle
  #          echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle
  #push to master , main, develop
  #pull request on main master