on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop
name: "Build & Release (Change APP Name)"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    environment: hallo
    env:
      APP_NAME: ${{vars.APP_NAME}}
      PACKAGE_NAME: ${{vars.PACKAGE_NAME}}
      LOGO: ${{vars.LOGO}}
      DOTENV: ${{vars.DOTENV}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.13.6"
          channel: 'stable'
          cache: true
      - name: Change App Name
        run: sed -i.bak "s/android:label=.*/android:label=\"$APP_NAME\"/g" android/app/src/main/AndroidManifest.xml
      - name: Change App Package Id
        run: |
          echo "android {  defaultConfig { applicationId '${PACKAGE_NAME}' }  }" > android/changePackage.gradle
          echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle
      # 6 Download logo
      - name: Download Logo Image
        id: app_logo
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: logo.png
          fileDir: './assets/images/'
          encodedString: $LOGO
      # 7 Download .env file
      - name: Download env file
        id: app_env
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: client.env
          encodedString: $DOTENV
      - run: flutter pub get
      - name: Generate App Assets
        run: flutter pub run flutter_launcher_icons
      - name: Start Android Release Build
        run: flutter build apk
      - name: Upload Android Release
        uses: actions/upload-artifact@v2
        with:
          name: android-release
          path: build/app/outputs/flutter-apk/app-release.apk

#echo "android {  defaultConfig { applicationId '${PACKAGE_NAME}' }  }" > android/changePackage.gradle
  #          echo "apply from: rootProject.file('changePackage.gradle')" >> android/app/build.gradle
  #push to master , main, develop
  #pull request on main master